-- MySQL Script generated by MySQL Workbench
-- 08/11/14 14:23:23
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema friends
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `friends` ;
CREATE SCHEMA IF NOT EXISTS `friends` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `friends` ;

-- -----------------------------------------------------
-- Table `friends`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user` ;

CREATE TABLE IF NOT EXISTS `friends`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `udid` VARCHAR(72) NOT NULL COMMENT 'ユニークなID',
  `name` VARCHAR(20) NOT NULL COMMENT 'ニックネーム',
  `sex` TINYINT UNSIGNED NOT NULL COMMENT '性別',
  `age` TINYINT UNSIGNED NOT NULL COMMENT '年齢',
  `country` TINYINT UNSIGNED NOT NULL COMMENT '国',
  `area` INT UNSIGNED NOT NULL COMMENT '地域',
  `request` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '友達申請許可',
  `publishing` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '公開設定',
  `push_id` VARCHAR(255) NOT NULL COMMENT 'プッシュ用のID',
  `profile` VARCHAR(150) NULL,
  `device` TINYINT NOT NULL COMMENT 'ユーザ端末',
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '有効無効',
  `image` MEDIUMBLOB NULL COMMENT '画像データ',
  `create_time` INT UNSIGNED NOT NULL,
  `login_time` INT UNSIGNED NOT NULL COMMENT '最終ログイン時間',
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udid_UNIQUE` (`udid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friends`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`friends` ;

CREATE TABLE IF NOT EXISTS `friends`.`friends` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id_1` INT UNSIGNED NOT NULL COMMENT 'ユーザID',
  `user_id_2` INT UNSIGNED NOT NULL COMMENT 'フレンドのID',
  `last_message_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_message_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT UNSIGNED NOT NULL,
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ids` (`user_id_1` ASC, `user_id_2` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `friends`.`user_photo_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_photo_0` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_photo_0` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'ユーザID',
  `no` INT UNSIGNED NOT NULL COMMENT 'ユーザ毎の自動連番',
  `image` MEDIUMBLOB NOT NULL COMMENT '画像のバイナリ',
  `create_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`no`, `user_id`))
ENGINE = InnoDB;

CREATE TABLE user_photo_1 LIKE user_photo_0;
CREATE TABLE user_photo_2 LIKE user_photo_0;
CREATE TABLE user_photo_3 LIKE user_photo_0;
CREATE TABLE user_photo_4 LIKE user_photo_0;
CREATE TABLE user_photo_5 LIKE user_photo_0;
CREATE TABLE user_photo_6 LIKE user_photo_0;
CREATE TABLE user_photo_7 LIKE user_photo_0;
CREATE TABLE user_photo_8 LIKE user_photo_0;
CREATE TABLE user_photo_9 LIKE user_photo_0;
CREATE TABLE user_photo_10 LIKE user_photo_0;
CREATE TABLE user_photo_11 LIKE user_photo_0;
CREATE TABLE user_photo_12 LIKE user_photo_0;
CREATE TABLE user_photo_13 LIKE user_photo_0;
CREATE TABLE user_photo_14 LIKE user_photo_0;
CREATE TABLE user_photo_15 LIKE user_photo_0;
CREATE TABLE user_photo_16 LIKE user_photo_0;
CREATE TABLE user_photo_17 LIKE user_photo_0;
CREATE TABLE user_photo_18 LIKE user_photo_0;
CREATE TABLE user_photo_19 LIKE user_photo_0;
CREATE TABLE user_photo_20 LIKE user_photo_0;
CREATE TABLE user_photo_21 LIKE user_photo_0;
CREATE TABLE user_photo_22 LIKE user_photo_0;
CREATE TABLE user_photo_23 LIKE user_photo_0;
CREATE TABLE user_photo_24 LIKE user_photo_0;
CREATE TABLE user_photo_25 LIKE user_photo_0;
CREATE TABLE user_photo_26 LIKE user_photo_0;
CREATE TABLE user_photo_27 LIKE user_photo_0;
CREATE TABLE user_photo_28 LIKE user_photo_0;
CREATE TABLE user_photo_29 LIKE user_photo_0;
CREATE TABLE user_photo_30 LIKE user_photo_0;
CREATE TABLE user_photo_31 LIKE user_photo_0;
CREATE TABLE user_photo_32 LIKE user_photo_0;
CREATE TABLE user_photo_33 LIKE user_photo_0;
CREATE TABLE user_photo_34 LIKE user_photo_0;
CREATE TABLE user_photo_35 LIKE user_photo_0;
CREATE TABLE user_photo_36 LIKE user_photo_0;
CREATE TABLE user_photo_37 LIKE user_photo_0;
CREATE TABLE user_photo_38 LIKE user_photo_0;
CREATE TABLE user_photo_39 LIKE user_photo_0;
CREATE TABLE user_photo_40 LIKE user_photo_0;
CREATE TABLE user_photo_41 LIKE user_photo_0;
CREATE TABLE user_photo_42 LIKE user_photo_0;
CREATE TABLE user_photo_43 LIKE user_photo_0;
CREATE TABLE user_photo_44 LIKE user_photo_0;
CREATE TABLE user_photo_45 LIKE user_photo_0;
CREATE TABLE user_photo_46 LIKE user_photo_0;
CREATE TABLE user_photo_47 LIKE user_photo_0;
CREATE TABLE user_photo_48 LIKE user_photo_0;
CREATE TABLE user_photo_49 LIKE user_photo_0;

-- -----------------------------------------------------
-- Table `friends`.`user_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_comment` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_comment` (
  `user_id` INT UNSIGNED NOT NULL,
  `comment_id` TINYINT UNSIGNED NOT NULL COMMENT 'コメント枠（1-6）',
  `title` VARCHAR(15) NULL COMMENT 'タイトル',
  `text` VARCHAR(140) NULL COMMENT '本文',
  `create_time` INT UNSIGNED NOT NULL,
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`comment_id`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friends`.`user_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_option` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_option` (
  `user_id` INT NOT NULL COMMENT 'user.id',
  `sex` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '0=all,1=men,2=women',
  `min_age` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '年齢最小',
  `max_age` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '年齢最大',
  `country` TINYINT UNSIGNED NULL DEFAULT 0,
  `area` INT UNSIGNED NULL DEFAULT 0,
  `view_friend` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `view_refuse` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `push_friend` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `push_chat` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friends`.`user_friend_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_friend_0` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_friend_0` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'ユーザID',
  `friend_id` INT UNSIGNED NOT NULL COMMENT 'フレンドのID',
  `friends_id` INT UNSIGNED NOT NULL,
  `push_chat` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`friend_id`, `user_id`))
ENGINE = InnoDB;

CREATE TABLE user_friend_1 LIKE user_friend_0;
CREATE TABLE user_friend_2 LIKE user_friend_0;
CREATE TABLE user_friend_3 LIKE user_friend_0;
CREATE TABLE user_friend_4 LIKE user_friend_0;
CREATE TABLE user_friend_5 LIKE user_friend_0;
CREATE TABLE user_friend_6 LIKE user_friend_0;
CREATE TABLE user_friend_7 LIKE user_friend_0;
CREATE TABLE user_friend_8 LIKE user_friend_0;
CREATE TABLE user_friend_9 LIKE user_friend_0;
CREATE TABLE user_friend_10 LIKE user_friend_0;
CREATE TABLE user_friend_11 LIKE user_friend_0;
CREATE TABLE user_friend_12 LIKE user_friend_0;
CREATE TABLE user_friend_13 LIKE user_friend_0;
CREATE TABLE user_friend_14 LIKE user_friend_0;
CREATE TABLE user_friend_15 LIKE user_friend_0;
CREATE TABLE user_friend_16 LIKE user_friend_0;
CREATE TABLE user_friend_17 LIKE user_friend_0;
CREATE TABLE user_friend_18 LIKE user_friend_0;
CREATE TABLE user_friend_19 LIKE user_friend_0;
CREATE TABLE user_friend_20 LIKE user_friend_0;
CREATE TABLE user_friend_21 LIKE user_friend_0;
CREATE TABLE user_friend_22 LIKE user_friend_0;
CREATE TABLE user_friend_23 LIKE user_friend_0;
CREATE TABLE user_friend_24 LIKE user_friend_0;
CREATE TABLE user_friend_25 LIKE user_friend_0;
CREATE TABLE user_friend_26 LIKE user_friend_0;
CREATE TABLE user_friend_27 LIKE user_friend_0;
CREATE TABLE user_friend_28 LIKE user_friend_0;
CREATE TABLE user_friend_29 LIKE user_friend_0;
CREATE TABLE user_friend_30 LIKE user_friend_0;
CREATE TABLE user_friend_31 LIKE user_friend_0;
CREATE TABLE user_friend_32 LIKE user_friend_0;
CREATE TABLE user_friend_33 LIKE user_friend_0;
CREATE TABLE user_friend_34 LIKE user_friend_0;
CREATE TABLE user_friend_35 LIKE user_friend_0;
CREATE TABLE user_friend_36 LIKE user_friend_0;
CREATE TABLE user_friend_37 LIKE user_friend_0;
CREATE TABLE user_friend_38 LIKE user_friend_0;
CREATE TABLE user_friend_39 LIKE user_friend_0;
CREATE TABLE user_friend_40 LIKE user_friend_0;
CREATE TABLE user_friend_41 LIKE user_friend_0;
CREATE TABLE user_friend_42 LIKE user_friend_0;
CREATE TABLE user_friend_43 LIKE user_friend_0;
CREATE TABLE user_friend_44 LIKE user_friend_0;
CREATE TABLE user_friend_45 LIKE user_friend_0;
CREATE TABLE user_friend_46 LIKE user_friend_0;
CREATE TABLE user_friend_47 LIKE user_friend_0;
CREATE TABLE user_friend_48 LIKE user_friend_0;
CREATE TABLE user_friend_49 LIKE user_friend_0;

-- -----------------------------------------------------
-- Table `friends`.`user_block_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_block_0` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_block_0` (
  `user_id` INT UNSIGNED NOT NULL,
  `block_id` INT UNSIGNED NOT NULL,
  `create_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `block_id`))
ENGINE = InnoDB;

CREATE TABLE user_block_1 LIKE user_block_0;
CREATE TABLE user_block_2 LIKE user_block_0;
CREATE TABLE user_block_3 LIKE user_block_0;
CREATE TABLE user_block_4 LIKE user_block_0;
CREATE TABLE user_block_5 LIKE user_block_0;
CREATE TABLE user_block_6 LIKE user_block_0;
CREATE TABLE user_block_7 LIKE user_block_0;
CREATE TABLE user_block_8 LIKE user_block_0;
CREATE TABLE user_block_9 LIKE user_block_0;
CREATE TABLE user_block_10 LIKE user_block_0;
CREATE TABLE user_block_11 LIKE user_block_0;
CREATE TABLE user_block_12 LIKE user_block_0;
CREATE TABLE user_block_13 LIKE user_block_0;
CREATE TABLE user_block_14 LIKE user_block_0;
CREATE TABLE user_block_15 LIKE user_block_0;
CREATE TABLE user_block_16 LIKE user_block_0;
CREATE TABLE user_block_17 LIKE user_block_0;
CREATE TABLE user_block_18 LIKE user_block_0;
CREATE TABLE user_block_19 LIKE user_block_0;
CREATE TABLE user_block_20 LIKE user_block_0;
CREATE TABLE user_block_21 LIKE user_block_0;
CREATE TABLE user_block_22 LIKE user_block_0;
CREATE TABLE user_block_23 LIKE user_block_0;
CREATE TABLE user_block_24 LIKE user_block_0;
CREATE TABLE user_block_25 LIKE user_block_0;
CREATE TABLE user_block_26 LIKE user_block_0;
CREATE TABLE user_block_27 LIKE user_block_0;
CREATE TABLE user_block_28 LIKE user_block_0;
CREATE TABLE user_block_29 LIKE user_block_0;
CREATE TABLE user_block_30 LIKE user_block_0;
CREATE TABLE user_block_31 LIKE user_block_0;
CREATE TABLE user_block_32 LIKE user_block_0;
CREATE TABLE user_block_33 LIKE user_block_0;
CREATE TABLE user_block_34 LIKE user_block_0;
CREATE TABLE user_block_35 LIKE user_block_0;
CREATE TABLE user_block_36 LIKE user_block_0;
CREATE TABLE user_block_37 LIKE user_block_0;
CREATE TABLE user_block_38 LIKE user_block_0;
CREATE TABLE user_block_39 LIKE user_block_0;
CREATE TABLE user_block_40 LIKE user_block_0;
CREATE TABLE user_block_41 LIKE user_block_0;
CREATE TABLE user_block_42 LIKE user_block_0;
CREATE TABLE user_block_43 LIKE user_block_0;
CREATE TABLE user_block_44 LIKE user_block_0;
CREATE TABLE user_block_45 LIKE user_block_0;
CREATE TABLE user_block_46 LIKE user_block_0;
CREATE TABLE user_block_47 LIKE user_block_0;
CREATE TABLE user_block_48 LIKE user_block_0;
CREATE TABLE user_block_49 LIKE user_block_0;

-- -----------------------------------------------------
-- Table `friends`.`user_block_from_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_blocker_0` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_blocker_0` (
  `user_id` INT UNSIGNED NOT NULL,
  `blocker_id` INT UNSIGNED NOT NULL,
  `create_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `blocker_id`))
ENGINE = InnoDB;

CREATE TABLE user_blocker_1 LIKE user_blocker_0;
CREATE TABLE user_blocker_2 LIKE user_blocker_0;
CREATE TABLE user_blocker_3 LIKE user_blocker_0;
CREATE TABLE user_blocker_4 LIKE user_blocker_0;
CREATE TABLE user_blocker_5 LIKE user_blocker_0;
CREATE TABLE user_blocker_6 LIKE user_blocker_0;
CREATE TABLE user_blocker_7 LIKE user_blocker_0;
CREATE TABLE user_blocker_8 LIKE user_blocker_0;
CREATE TABLE user_blocker_9 LIKE user_blocker_0;
CREATE TABLE user_blocker_10 LIKE user_blocker_0;
CREATE TABLE user_blocker_11 LIKE user_blocker_0;
CREATE TABLE user_blocker_12 LIKE user_blocker_0;
CREATE TABLE user_blocker_13 LIKE user_blocker_0;
CREATE TABLE user_blocker_14 LIKE user_blocker_0;
CREATE TABLE user_blocker_15 LIKE user_blocker_0;
CREATE TABLE user_blocker_16 LIKE user_blocker_0;
CREATE TABLE user_blocker_17 LIKE user_blocker_0;
CREATE TABLE user_blocker_18 LIKE user_blocker_0;
CREATE TABLE user_blocker_19 LIKE user_blocker_0;
CREATE TABLE user_blocker_20 LIKE user_blocker_0;
CREATE TABLE user_blocker_21 LIKE user_blocker_0;
CREATE TABLE user_blocker_22 LIKE user_blocker_0;
CREATE TABLE user_blocker_23 LIKE user_blocker_0;
CREATE TABLE user_blocker_24 LIKE user_blocker_0;
CREATE TABLE user_blocker_25 LIKE user_blocker_0;
CREATE TABLE user_blocker_26 LIKE user_blocker_0;
CREATE TABLE user_blocker_27 LIKE user_blocker_0;
CREATE TABLE user_blocker_28 LIKE user_blocker_0;
CREATE TABLE user_blocker_29 LIKE user_blocker_0;
CREATE TABLE user_blocker_30 LIKE user_blocker_0;
CREATE TABLE user_blocker_31 LIKE user_blocker_0;
CREATE TABLE user_blocker_32 LIKE user_blocker_0;
CREATE TABLE user_blocker_33 LIKE user_blocker_0;
CREATE TABLE user_blocker_34 LIKE user_blocker_0;
CREATE TABLE user_blocker_35 LIKE user_blocker_0;
CREATE TABLE user_blocker_36 LIKE user_blocker_0;
CREATE TABLE user_blocker_37 LIKE user_blocker_0;
CREATE TABLE user_blocker_38 LIKE user_blocker_0;
CREATE TABLE user_blocker_39 LIKE user_blocker_0;
CREATE TABLE user_blocker_40 LIKE user_blocker_0;
CREATE TABLE user_blocker_41 LIKE user_blocker_0;
CREATE TABLE user_blocker_42 LIKE user_blocker_0;
CREATE TABLE user_blocker_43 LIKE user_blocker_0;
CREATE TABLE user_blocker_44 LIKE user_blocker_0;
CREATE TABLE user_blocker_45 LIKE user_blocker_0;
CREATE TABLE user_blocker_46 LIKE user_blocker_0;
CREATE TABLE user_blocker_47 LIKE user_blocker_0;
CREATE TABLE user_blocker_48 LIKE user_blocker_0;
CREATE TABLE user_blocker_49 LIKE user_blocker_0;

-- -----------------------------------------------------
-- Table `friends`.`user_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_token` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_token` (
  `id` INT UNSIGNED NOT NULL,
  `token` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `friends`.`user_memo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_memo` ;
CREATE TABLE `friends`.`user_memo` (
  `id` int(10) unsigned NOT NULL,
  `memo` text NOT NULL,
  `update_time` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;

-- -----------------------------------------------------
-- Table `friends`.`user_ban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_ban` ;
CREATE TABLE `friends`.`user_ban` (
  `id` int(10) unsigned NOT NULL,
  `available` tinyint(3) unsigned NOT NULL,
  `reason` varchar(100) NOT NULL,
  `start_time` int(10) unsigned NOT NULL,
  `end_time` int(10) unsigned NOT NULL,
  `create_time` int(10) unsigned NOT NULL,
  `update_time` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `friends`.`user_ban_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_ban_history` ;
CREATE TABLE `friends`.`user_ban_history` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `reason` varchar(100) NOT NULL,
  `start_time` int(10) unsigned NOT NULL,
  `end_time` int(10) unsigned NOT NULL,
  `create_time` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;

-- -----------------------------------------------------
-- Table `friends`.`user_group_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_group_0` ;
DROP TABLE IF EXISTS `friends`.`user_group_1` ;
DROP TABLE IF EXISTS `friends`.`user_group_2` ;
DROP TABLE IF EXISTS `friends`.`user_group_3` ;
DROP TABLE IF EXISTS `friends`.`user_group_4` ;
DROP TABLE IF EXISTS `friends`.`user_group_5` ;
DROP TABLE IF EXISTS `friends`.`user_group_6` ;
DROP TABLE IF EXISTS `friends`.`user_group_7` ;
DROP TABLE IF EXISTS `friends`.`user_group_8` ;
DROP TABLE IF EXISTS `friends`.`user_group_9` ;
DROP TABLE IF EXISTS `friends`.`user_group_10` ;
DROP TABLE IF EXISTS `friends`.`user_group_11` ;
DROP TABLE IF EXISTS `friends`.`user_group_12` ;
DROP TABLE IF EXISTS `friends`.`user_group_13` ;
DROP TABLE IF EXISTS `friends`.`user_group_14` ;
DROP TABLE IF EXISTS `friends`.`user_group_15` ;
DROP TABLE IF EXISTS `friends`.`user_group_16` ;
DROP TABLE IF EXISTS `friends`.`user_group_17` ;
DROP TABLE IF EXISTS `friends`.`user_group_18` ;
DROP TABLE IF EXISTS `friends`.`user_group_19` ;
DROP TABLE IF EXISTS `friends`.`user_group_20` ;
DROP TABLE IF EXISTS `friends`.`user_group_21` ;
DROP TABLE IF EXISTS `friends`.`user_group_22` ;
DROP TABLE IF EXISTS `friends`.`user_group_23` ;
DROP TABLE IF EXISTS `friends`.`user_group_24` ;
DROP TABLE IF EXISTS `friends`.`user_group_25` ;
DROP TABLE IF EXISTS `friends`.`user_group_26` ;
DROP TABLE IF EXISTS `friends`.`user_group_27` ;
DROP TABLE IF EXISTS `friends`.`user_group_28` ;
DROP TABLE IF EXISTS `friends`.`user_group_29` ;
DROP TABLE IF EXISTS `friends`.`user_group_30` ;
DROP TABLE IF EXISTS `friends`.`user_group_31` ;
DROP TABLE IF EXISTS `friends`.`user_group_32` ;
DROP TABLE IF EXISTS `friends`.`user_group_33` ;
DROP TABLE IF EXISTS `friends`.`user_group_34` ;
DROP TABLE IF EXISTS `friends`.`user_group_35` ;
DROP TABLE IF EXISTS `friends`.`user_group_36` ;
DROP TABLE IF EXISTS `friends`.`user_group_37` ;
DROP TABLE IF EXISTS `friends`.`user_group_38` ;
DROP TABLE IF EXISTS `friends`.`user_group_39` ;
DROP TABLE IF EXISTS `friends`.`user_group_40` ;
DROP TABLE IF EXISTS `friends`.`user_group_41` ;
DROP TABLE IF EXISTS `friends`.`user_group_42` ;
DROP TABLE IF EXISTS `friends`.`user_group_43` ;
DROP TABLE IF EXISTS `friends`.`user_group_44` ;
DROP TABLE IF EXISTS `friends`.`user_group_45` ;
DROP TABLE IF EXISTS `friends`.`user_group_46` ;
DROP TABLE IF EXISTS `friends`.`user_group_47` ;
DROP TABLE IF EXISTS `friends`.`user_group_48` ;
DROP TABLE IF EXISTS `friends`.`user_group_49` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_group_0` (
  `user_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `user_group_log_id` INT UNSIGNED NOT NULL,
  `last_message_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `push_chat` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `create_time` INT UNSIGNED NOT NULL,
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`))
ENGINE = InnoDB;

CREATE TABLE user_group_1 LIKE user_group_0;
CREATE TABLE user_group_2 LIKE user_group_0;
CREATE TABLE user_group_3 LIKE user_group_0;
CREATE TABLE user_group_4 LIKE user_group_0;
CREATE TABLE user_group_5 LIKE user_group_0;
CREATE TABLE user_group_6 LIKE user_group_0;
CREATE TABLE user_group_7 LIKE user_group_0;
CREATE TABLE user_group_8 LIKE user_group_0;
CREATE TABLE user_group_9 LIKE user_group_0;
CREATE TABLE user_group_10 LIKE user_group_0;
CREATE TABLE user_group_11 LIKE user_group_0;
CREATE TABLE user_group_12 LIKE user_group_0;
CREATE TABLE user_group_13 LIKE user_group_0;
CREATE TABLE user_group_14 LIKE user_group_0;
CREATE TABLE user_group_15 LIKE user_group_0;
CREATE TABLE user_group_16 LIKE user_group_0;
CREATE TABLE user_group_17 LIKE user_group_0;
CREATE TABLE user_group_18 LIKE user_group_0;
CREATE TABLE user_group_19 LIKE user_group_0;
CREATE TABLE user_group_20 LIKE user_group_0;
CREATE TABLE user_group_21 LIKE user_group_0;
CREATE TABLE user_group_22 LIKE user_group_0;
CREATE TABLE user_group_23 LIKE user_group_0;
CREATE TABLE user_group_24 LIKE user_group_0;
CREATE TABLE user_group_25 LIKE user_group_0;
CREATE TABLE user_group_26 LIKE user_group_0;
CREATE TABLE user_group_27 LIKE user_group_0;
CREATE TABLE user_group_28 LIKE user_group_0;
CREATE TABLE user_group_29 LIKE user_group_0;
CREATE TABLE user_group_30 LIKE user_group_0;
CREATE TABLE user_group_31 LIKE user_group_0;
CREATE TABLE user_group_32 LIKE user_group_0;
CREATE TABLE user_group_33 LIKE user_group_0;
CREATE TABLE user_group_34 LIKE user_group_0;
CREATE TABLE user_group_35 LIKE user_group_0;
CREATE TABLE user_group_36 LIKE user_group_0;
CREATE TABLE user_group_37 LIKE user_group_0;
CREATE TABLE user_group_38 LIKE user_group_0;
CREATE TABLE user_group_39 LIKE user_group_0;
CREATE TABLE user_group_40 LIKE user_group_0;
CREATE TABLE user_group_41 LIKE user_group_0;
CREATE TABLE user_group_42 LIKE user_group_0;
CREATE TABLE user_group_43 LIKE user_group_0;
CREATE TABLE user_group_44 LIKE user_group_0;
CREATE TABLE user_group_45 LIKE user_group_0;
CREATE TABLE user_group_46 LIKE user_group_0;
CREATE TABLE user_group_47 LIKE user_group_0;
CREATE TABLE user_group_48 LIKE user_group_0;
CREATE TABLE user_group_49 LIKE user_group_0;

-- -----------------------------------------------------
-- Table `friends`.`user_group_log_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`user_group_log_0` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_1` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_2` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_3` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_4` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_5` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_6` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_7` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_8` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_9` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_10` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_11` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_12` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_13` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_14` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_15` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_16` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_17` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_18` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_19` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_20` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_21` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_22` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_23` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_24` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_25` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_26` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_27` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_28` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_29` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_30` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_31` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_32` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_33` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_34` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_35` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_36` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_37` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_38` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_39` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_40` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_41` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_42` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_43` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_44` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_45` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_46` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_47` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_48` ;
DROP TABLE IF EXISTS `friends`.`user_group_log_49` ;

CREATE TABLE IF NOT EXISTS `friends`.`user_group_log_0` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NOT NULL,
  `invitation_id` INT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `deleter_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `invitation_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `add_group_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `leave_group_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_message_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `update_time` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `gets` (`user_id` ASC,`group_id` ASC))
ENGINE = InnoDB;

CREATE TABLE user_group_log_1 LIKE user_group_log_0;
CREATE TABLE user_group_log_2 LIKE user_group_log_0;
CREATE TABLE user_group_log_3 LIKE user_group_log_0;
CREATE TABLE user_group_log_4 LIKE user_group_log_0;
CREATE TABLE user_group_log_5 LIKE user_group_log_0;
CREATE TABLE user_group_log_6 LIKE user_group_log_0;
CREATE TABLE user_group_log_7 LIKE user_group_log_0;
CREATE TABLE user_group_log_8 LIKE user_group_log_0;
CREATE TABLE user_group_log_9 LIKE user_group_log_0;
CREATE TABLE user_group_log_10 LIKE user_group_log_0;
CREATE TABLE user_group_log_11 LIKE user_group_log_0;
CREATE TABLE user_group_log_12 LIKE user_group_log_0;
CREATE TABLE user_group_log_13 LIKE user_group_log_0;
CREATE TABLE user_group_log_14 LIKE user_group_log_0;
CREATE TABLE user_group_log_15 LIKE user_group_log_0;
CREATE TABLE user_group_log_16 LIKE user_group_log_0;
CREATE TABLE user_group_log_17 LIKE user_group_log_0;
CREATE TABLE user_group_log_18 LIKE user_group_log_0;
CREATE TABLE user_group_log_19 LIKE user_group_log_0;
CREATE TABLE user_group_log_20 LIKE user_group_log_0;
CREATE TABLE user_group_log_21 LIKE user_group_log_0;
CREATE TABLE user_group_log_22 LIKE user_group_log_0;
CREATE TABLE user_group_log_23 LIKE user_group_log_0;
CREATE TABLE user_group_log_24 LIKE user_group_log_0;
CREATE TABLE user_group_log_25 LIKE user_group_log_0;
CREATE TABLE user_group_log_26 LIKE user_group_log_0;
CREATE TABLE user_group_log_27 LIKE user_group_log_0;
CREATE TABLE user_group_log_28 LIKE user_group_log_0;
CREATE TABLE user_group_log_29 LIKE user_group_log_0;
CREATE TABLE user_group_log_30 LIKE user_group_log_0;
CREATE TABLE user_group_log_31 LIKE user_group_log_0;
CREATE TABLE user_group_log_32 LIKE user_group_log_0;
CREATE TABLE user_group_log_33 LIKE user_group_log_0;
CREATE TABLE user_group_log_34 LIKE user_group_log_0;
CREATE TABLE user_group_log_35 LIKE user_group_log_0;
CREATE TABLE user_group_log_36 LIKE user_group_log_0;
CREATE TABLE user_group_log_37 LIKE user_group_log_0;
CREATE TABLE user_group_log_38 LIKE user_group_log_0;
CREATE TABLE user_group_log_39 LIKE user_group_log_0;
CREATE TABLE user_group_log_40 LIKE user_group_log_0;
CREATE TABLE user_group_log_41 LIKE user_group_log_0;
CREATE TABLE user_group_log_42 LIKE user_group_log_0;
CREATE TABLE user_group_log_43 LIKE user_group_log_0;
CREATE TABLE user_group_log_44 LIKE user_group_log_0;
CREATE TABLE user_group_log_45 LIKE user_group_log_0;
CREATE TABLE user_group_log_46 LIKE user_group_log_0;
CREATE TABLE user_group_log_47 LIKE user_group_log_0;
CREATE TABLE user_group_log_48 LIKE user_group_log_0;
CREATE TABLE user_group_log_49 LIKE user_group_log_0;

-- -----------------------------------------------------
-- Table `friends`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`report` ;

CREATE TABLE IF NOT EXISTS `friends`.`report` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `reporter_id` INT UNSIGNED NOT NULL,
  `message` VARCHAR(400) NOT NULL,
  `create_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `friends`.`push_queue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`push_queue` ;

CREATE TABLE IF NOT EXISTS `friends`.`push_queue` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_id` INT UNSIGNED NOT NULL,
  `to_id` INT UNSIGNED NOT NULL,
  `message` VARCHAR(200) NOT NULL COMMENT '送信メッセージ',
  `type` TINYINT UNSIGNED NOT NULL,
  `create_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MEMORY;

-- -----------------------------------------------------
-- Table `friends`.`push_queue_lock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`push_queue_lock` ;

CREATE TABLE IF NOT EXISTS `friends`.`push_queue_lock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `create_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MEMORY;

-- -----------------------------------------------------
-- Table `friends`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`question` ;

CREATE TABLE IF NOT EXISTS `friends`.`question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR UNSIGNED NOT NULL,
  `create_time` INT UNSIGNED NOT NULL,
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `friends`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`groups` ;

CREATE TABLE IF NOT EXISTS `friends`.`groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `create_user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `image` MEDIUMBLOB NULL COMMENT '画像データ',
  `delete_flag` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `last_message_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_message_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT UNSIGNED NOT NULL,
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `friends`.`group_user_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`group_user_0` ;
DROP TABLE IF EXISTS `friends`.`group_user_1` ;
DROP TABLE IF EXISTS `friends`.`group_user_2` ;
DROP TABLE IF EXISTS `friends`.`group_user_3` ;
DROP TABLE IF EXISTS `friends`.`group_user_4` ;
DROP TABLE IF EXISTS `friends`.`group_user_5` ;
DROP TABLE IF EXISTS `friends`.`group_user_6` ;
DROP TABLE IF EXISTS `friends`.`group_user_7` ;
DROP TABLE IF EXISTS `friends`.`group_user_8` ;
DROP TABLE IF EXISTS `friends`.`group_user_9` ;
DROP TABLE IF EXISTS `friends`.`group_user_10` ;
DROP TABLE IF EXISTS `friends`.`group_user_11` ;
DROP TABLE IF EXISTS `friends`.`group_user_12` ;
DROP TABLE IF EXISTS `friends`.`group_user_13` ;
DROP TABLE IF EXISTS `friends`.`group_user_14` ;
DROP TABLE IF EXISTS `friends`.`group_user_15` ;
DROP TABLE IF EXISTS `friends`.`group_user_16` ;
DROP TABLE IF EXISTS `friends`.`group_user_17` ;
DROP TABLE IF EXISTS `friends`.`group_user_18` ;
DROP TABLE IF EXISTS `friends`.`group_user_19` ;
DROP TABLE IF EXISTS `friends`.`group_user_20` ;
DROP TABLE IF EXISTS `friends`.`group_user_21` ;
DROP TABLE IF EXISTS `friends`.`group_user_22` ;
DROP TABLE IF EXISTS `friends`.`group_user_23` ;
DROP TABLE IF EXISTS `friends`.`group_user_24` ;
DROP TABLE IF EXISTS `friends`.`group_user_25` ;
DROP TABLE IF EXISTS `friends`.`group_user_26` ;
DROP TABLE IF EXISTS `friends`.`group_user_27` ;
DROP TABLE IF EXISTS `friends`.`group_user_28` ;
DROP TABLE IF EXISTS `friends`.`group_user_29` ;
DROP TABLE IF EXISTS `friends`.`group_user_30` ;
DROP TABLE IF EXISTS `friends`.`group_user_31` ;
DROP TABLE IF EXISTS `friends`.`group_user_32` ;
DROP TABLE IF EXISTS `friends`.`group_user_33` ;
DROP TABLE IF EXISTS `friends`.`group_user_34` ;
DROP TABLE IF EXISTS `friends`.`group_user_35` ;
DROP TABLE IF EXISTS `friends`.`group_user_36` ;
DROP TABLE IF EXISTS `friends`.`group_user_37` ;
DROP TABLE IF EXISTS `friends`.`group_user_38` ;
DROP TABLE IF EXISTS `friends`.`group_user_39` ;
DROP TABLE IF EXISTS `friends`.`group_user_40` ;
DROP TABLE IF EXISTS `friends`.`group_user_41` ;
DROP TABLE IF EXISTS `friends`.`group_user_42` ;
DROP TABLE IF EXISTS `friends`.`group_user_43` ;
DROP TABLE IF EXISTS `friends`.`group_user_44` ;
DROP TABLE IF EXISTS `friends`.`group_user_45` ;
DROP TABLE IF EXISTS `friends`.`group_user_46` ;
DROP TABLE IF EXISTS `friends`.`group_user_47` ;
DROP TABLE IF EXISTS `friends`.`group_user_48` ;
DROP TABLE IF EXISTS `friends`.`group_user_49` ;

CREATE TABLE IF NOT EXISTS `friends`.`group_user_0` (
  `group_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `invitation_id` INT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `deleter_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT UNSIGNED NOT NULL,
  `update_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`group_id`, `user_id`))
ENGINE = InnoDB;

CREATE TABLE group_user_1 LIKE group_user_0;
CREATE TABLE group_user_2 LIKE group_user_0;
CREATE TABLE group_user_3 LIKE group_user_0;
CREATE TABLE group_user_4 LIKE group_user_0;
CREATE TABLE group_user_5 LIKE group_user_0;
CREATE TABLE group_user_6 LIKE group_user_0;
CREATE TABLE group_user_7 LIKE group_user_0;
CREATE TABLE group_user_8 LIKE group_user_0;
CREATE TABLE group_user_9 LIKE group_user_0;
CREATE TABLE group_user_10 LIKE group_user_0;
CREATE TABLE group_user_11 LIKE group_user_0;
CREATE TABLE group_user_12 LIKE group_user_0;
CREATE TABLE group_user_13 LIKE group_user_0;
CREATE TABLE group_user_14 LIKE group_user_0;
CREATE TABLE group_user_15 LIKE group_user_0;
CREATE TABLE group_user_16 LIKE group_user_0;
CREATE TABLE group_user_17 LIKE group_user_0;
CREATE TABLE group_user_18 LIKE group_user_0;
CREATE TABLE group_user_19 LIKE group_user_0;
CREATE TABLE group_user_20 LIKE group_user_0;
CREATE TABLE group_user_21 LIKE group_user_0;
CREATE TABLE group_user_22 LIKE group_user_0;
CREATE TABLE group_user_23 LIKE group_user_0;
CREATE TABLE group_user_24 LIKE group_user_0;
CREATE TABLE group_user_25 LIKE group_user_0;
CREATE TABLE group_user_26 LIKE group_user_0;
CREATE TABLE group_user_27 LIKE group_user_0;
CREATE TABLE group_user_28 LIKE group_user_0;
CREATE TABLE group_user_29 LIKE group_user_0;
CREATE TABLE group_user_30 LIKE group_user_0;
CREATE TABLE group_user_31 LIKE group_user_0;
CREATE TABLE group_user_32 LIKE group_user_0;
CREATE TABLE group_user_33 LIKE group_user_0;
CREATE TABLE group_user_34 LIKE group_user_0;
CREATE TABLE group_user_35 LIKE group_user_0;
CREATE TABLE group_user_36 LIKE group_user_0;
CREATE TABLE group_user_37 LIKE group_user_0;
CREATE TABLE group_user_38 LIKE group_user_0;
CREATE TABLE group_user_39 LIKE group_user_0;
CREATE TABLE group_user_40 LIKE group_user_0;
CREATE TABLE group_user_41 LIKE group_user_0;
CREATE TABLE group_user_42 LIKE group_user_0;
CREATE TABLE group_user_43 LIKE group_user_0;
CREATE TABLE group_user_44 LIKE group_user_0;
CREATE TABLE group_user_45 LIKE group_user_0;
CREATE TABLE group_user_46 LIKE group_user_0;
CREATE TABLE group_user_47 LIKE group_user_0;
CREATE TABLE group_user_48 LIKE group_user_0;
CREATE TABLE group_user_49 LIKE group_user_0;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;