-- MySQL Script generated by MySQL Workbench
-- 08/11/14 14:23:23
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema friends_user_request
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `friends_user_request` ;
CREATE SCHEMA IF NOT EXISTS `friends_user_request` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `friends_user_request` ;

-- -----------------------------------------------------
-- Table `friends_user_request`.`user_request_from_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends_user_request`.`user_request_from_0` ;

CREATE TABLE IF NOT EXISTS `friends_user_request`.`user_request_from_0` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'フレンド申請したユーザのID',
  `to_id` INT UNSIGNED NOT NULL COMMENT 'フレンド申請されたユーザのID',
  `message_id` INT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1=申請中,2=成立,3=拒否',
  `delete_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '1=削除',
  `create_time` INT UNSIGNED NOT NULL COMMENT '作成時間',
  `update_time` INT UNSIGNED NOT NULL COMMENT '更新時間',
  PRIMARY KEY (`user_id`, `to_id`))
ENGINE = InnoDB;

CREATE TABLE user_request_from_1 LIKE user_request_from_0;
CREATE TABLE user_request_from_2 LIKE user_request_from_0;
CREATE TABLE user_request_from_3 LIKE user_request_from_0;
CREATE TABLE user_request_from_4 LIKE user_request_from_0;
CREATE TABLE user_request_from_5 LIKE user_request_from_0;
CREATE TABLE user_request_from_6 LIKE user_request_from_0;
CREATE TABLE user_request_from_7 LIKE user_request_from_0;
CREATE TABLE user_request_from_8 LIKE user_request_from_0;
CREATE TABLE user_request_from_9 LIKE user_request_from_0;
CREATE TABLE user_request_from_10 LIKE user_request_from_0;
CREATE TABLE user_request_from_11 LIKE user_request_from_0;
CREATE TABLE user_request_from_12 LIKE user_request_from_0;
CREATE TABLE user_request_from_13 LIKE user_request_from_0;
CREATE TABLE user_request_from_14 LIKE user_request_from_0;
CREATE TABLE user_request_from_15 LIKE user_request_from_0;
CREATE TABLE user_request_from_16 LIKE user_request_from_0;
CREATE TABLE user_request_from_17 LIKE user_request_from_0;
CREATE TABLE user_request_from_18 LIKE user_request_from_0;
CREATE TABLE user_request_from_19 LIKE user_request_from_0;
CREATE TABLE user_request_from_20 LIKE user_request_from_0;
CREATE TABLE user_request_from_21 LIKE user_request_from_0;
CREATE TABLE user_request_from_22 LIKE user_request_from_0;
CREATE TABLE user_request_from_23 LIKE user_request_from_0;
CREATE TABLE user_request_from_24 LIKE user_request_from_0;
CREATE TABLE user_request_from_25 LIKE user_request_from_0;
CREATE TABLE user_request_from_26 LIKE user_request_from_0;
CREATE TABLE user_request_from_27 LIKE user_request_from_0;
CREATE TABLE user_request_from_28 LIKE user_request_from_0;
CREATE TABLE user_request_from_29 LIKE user_request_from_0;
CREATE TABLE user_request_from_30 LIKE user_request_from_0;
CREATE TABLE user_request_from_31 LIKE user_request_from_0;
CREATE TABLE user_request_from_32 LIKE user_request_from_0;
CREATE TABLE user_request_from_33 LIKE user_request_from_0;
CREATE TABLE user_request_from_34 LIKE user_request_from_0;
CREATE TABLE user_request_from_35 LIKE user_request_from_0;
CREATE TABLE user_request_from_36 LIKE user_request_from_0;
CREATE TABLE user_request_from_37 LIKE user_request_from_0;
CREATE TABLE user_request_from_38 LIKE user_request_from_0;
CREATE TABLE user_request_from_39 LIKE user_request_from_0;
CREATE TABLE user_request_from_40 LIKE user_request_from_0;
CREATE TABLE user_request_from_41 LIKE user_request_from_0;
CREATE TABLE user_request_from_42 LIKE user_request_from_0;
CREATE TABLE user_request_from_43 LIKE user_request_from_0;
CREATE TABLE user_request_from_44 LIKE user_request_from_0;
CREATE TABLE user_request_from_45 LIKE user_request_from_0;
CREATE TABLE user_request_from_46 LIKE user_request_from_0;
CREATE TABLE user_request_from_47 LIKE user_request_from_0;
CREATE TABLE user_request_from_48 LIKE user_request_from_0;
CREATE TABLE user_request_from_49 LIKE user_request_from_0;

-- -----------------------------------------------------
-- Table `friends_user_request`.`user_request_to_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends_user_request`.`user_request_to_0` ;

CREATE TABLE IF NOT EXISTS `friends_user_request`.`user_request_to_0` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'フレンド申請されたユーザのID',
  `from_id` INT UNSIGNED NOT NULL COMMENT 'フレンド申請したユーザのID',
  `message_id` INT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'ステータス',
  `delete_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT UNSIGNED NOT NULL COMMENT '作成時間',
  `update_time` INT UNSIGNED NOT NULL COMMENT '更新時間',
  PRIMARY KEY (`user_id`, `from_id`))
ENGINE = InnoDB;

CREATE TABLE user_request_to_1 LIKE user_request_to_0;
CREATE TABLE user_request_to_2 LIKE user_request_to_0;
CREATE TABLE user_request_to_3 LIKE user_request_to_0;
CREATE TABLE user_request_to_4 LIKE user_request_to_0;
CREATE TABLE user_request_to_5 LIKE user_request_to_0;
CREATE TABLE user_request_to_6 LIKE user_request_to_0;
CREATE TABLE user_request_to_7 LIKE user_request_to_0;
CREATE TABLE user_request_to_8 LIKE user_request_to_0;
CREATE TABLE user_request_to_9 LIKE user_request_to_0;
CREATE TABLE user_request_to_10 LIKE user_request_to_0;
CREATE TABLE user_request_to_11 LIKE user_request_to_0;
CREATE TABLE user_request_to_12 LIKE user_request_to_0;
CREATE TABLE user_request_to_13 LIKE user_request_to_0;
CREATE TABLE user_request_to_14 LIKE user_request_to_0;
CREATE TABLE user_request_to_15 LIKE user_request_to_0;
CREATE TABLE user_request_to_16 LIKE user_request_to_0;
CREATE TABLE user_request_to_17 LIKE user_request_to_0;
CREATE TABLE user_request_to_18 LIKE user_request_to_0;
CREATE TABLE user_request_to_19 LIKE user_request_to_0;
CREATE TABLE user_request_to_20 LIKE user_request_to_0;
CREATE TABLE user_request_to_21 LIKE user_request_to_0;
CREATE TABLE user_request_to_22 LIKE user_request_to_0;
CREATE TABLE user_request_to_23 LIKE user_request_to_0;
CREATE TABLE user_request_to_24 LIKE user_request_to_0;
CREATE TABLE user_request_to_25 LIKE user_request_to_0;
CREATE TABLE user_request_to_26 LIKE user_request_to_0;
CREATE TABLE user_request_to_27 LIKE user_request_to_0;
CREATE TABLE user_request_to_28 LIKE user_request_to_0;
CREATE TABLE user_request_to_29 LIKE user_request_to_0;
CREATE TABLE user_request_to_30 LIKE user_request_to_0;
CREATE TABLE user_request_to_31 LIKE user_request_to_0;
CREATE TABLE user_request_to_32 LIKE user_request_to_0;
CREATE TABLE user_request_to_33 LIKE user_request_to_0;
CREATE TABLE user_request_to_34 LIKE user_request_to_0;
CREATE TABLE user_request_to_35 LIKE user_request_to_0;
CREATE TABLE user_request_to_36 LIKE user_request_to_0;
CREATE TABLE user_request_to_37 LIKE user_request_to_0;
CREATE TABLE user_request_to_38 LIKE user_request_to_0;
CREATE TABLE user_request_to_39 LIKE user_request_to_0;
CREATE TABLE user_request_to_40 LIKE user_request_to_0;
CREATE TABLE user_request_to_41 LIKE user_request_to_0;
CREATE TABLE user_request_to_42 LIKE user_request_to_0;
CREATE TABLE user_request_to_43 LIKE user_request_to_0;
CREATE TABLE user_request_to_44 LIKE user_request_to_0;
CREATE TABLE user_request_to_45 LIKE user_request_to_0;
CREATE TABLE user_request_to_46 LIKE user_request_to_0;
CREATE TABLE user_request_to_47 LIKE user_request_to_0;
CREATE TABLE user_request_to_48 LIKE user_request_to_0;
CREATE TABLE user_request_to_49 LIKE user_request_to_0;

-- -----------------------------------------------------
-- Table `friends_user_request`.`user_request_message_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends_user_request`.`user_request_message_0` ;

CREATE TABLE IF NOT EXISTS `friends_user_request`.`user_request_message_0` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL COMMENT 'FROM側のuser.id',
  `message` VARCHAR(70) NOT NULL COMMENT 'リクエスト文',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE user_request_message_1 LIKE user_request_message_0;
CREATE TABLE user_request_message_2 LIKE user_request_message_0;
CREATE TABLE user_request_message_3 LIKE user_request_message_0;
CREATE TABLE user_request_message_4 LIKE user_request_message_0;
CREATE TABLE user_request_message_5 LIKE user_request_message_0;
CREATE TABLE user_request_message_6 LIKE user_request_message_0;
CREATE TABLE user_request_message_7 LIKE user_request_message_0;
CREATE TABLE user_request_message_8 LIKE user_request_message_0;
CREATE TABLE user_request_message_9 LIKE user_request_message_0;
CREATE TABLE user_request_message_10 LIKE user_request_message_0;
CREATE TABLE user_request_message_11 LIKE user_request_message_0;
CREATE TABLE user_request_message_12 LIKE user_request_message_0;
CREATE TABLE user_request_message_13 LIKE user_request_message_0;
CREATE TABLE user_request_message_14 LIKE user_request_message_0;
CREATE TABLE user_request_message_15 LIKE user_request_message_0;
CREATE TABLE user_request_message_16 LIKE user_request_message_0;
CREATE TABLE user_request_message_17 LIKE user_request_message_0;
CREATE TABLE user_request_message_18 LIKE user_request_message_0;
CREATE TABLE user_request_message_19 LIKE user_request_message_0;
CREATE TABLE user_request_message_20 LIKE user_request_message_0;
CREATE TABLE user_request_message_21 LIKE user_request_message_0;
CREATE TABLE user_request_message_22 LIKE user_request_message_0;
CREATE TABLE user_request_message_23 LIKE user_request_message_0;
CREATE TABLE user_request_message_24 LIKE user_request_message_0;
CREATE TABLE user_request_message_25 LIKE user_request_message_0;
CREATE TABLE user_request_message_26 LIKE user_request_message_0;
CREATE TABLE user_request_message_27 LIKE user_request_message_0;
CREATE TABLE user_request_message_28 LIKE user_request_message_0;
CREATE TABLE user_request_message_29 LIKE user_request_message_0;
CREATE TABLE user_request_message_30 LIKE user_request_message_0;
CREATE TABLE user_request_message_31 LIKE user_request_message_0;
CREATE TABLE user_request_message_32 LIKE user_request_message_0;
CREATE TABLE user_request_message_33 LIKE user_request_message_0;
CREATE TABLE user_request_message_34 LIKE user_request_message_0;
CREATE TABLE user_request_message_35 LIKE user_request_message_0;
CREATE TABLE user_request_message_36 LIKE user_request_message_0;
CREATE TABLE user_request_message_37 LIKE user_request_message_0;
CREATE TABLE user_request_message_38 LIKE user_request_message_0;
CREATE TABLE user_request_message_39 LIKE user_request_message_0;
CREATE TABLE user_request_message_40 LIKE user_request_message_0;
CREATE TABLE user_request_message_41 LIKE user_request_message_0;
CREATE TABLE user_request_message_42 LIKE user_request_message_0;
CREATE TABLE user_request_message_43 LIKE user_request_message_0;
CREATE TABLE user_request_message_44 LIKE user_request_message_0;
CREATE TABLE user_request_message_45 LIKE user_request_message_0;
CREATE TABLE user_request_message_46 LIKE user_request_message_0;
CREATE TABLE user_request_message_47 LIKE user_request_message_0;
CREATE TABLE user_request_message_48 LIKE user_request_message_0;
CREATE TABLE user_request_message_49 LIKE user_request_message_0;